// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3z-T6zcXHlYCA5PHo4QZa6Z5ZcGZKwo',
    appId: '1:413446513130:web:771d16799823948cd59293',
    messagingSenderId: '413446513130',
    projectId: 'app-fire-6dadc',
    authDomain: 'app-fire-6dadc.firebaseapp.com',
    databaseURL: 'https://app-fire-6dadc-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-6dadc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjl1PowlJFA-yyZWHq6RJzoMEt-yBuPw',
    appId: '1:413446513130:android:e0661cde381f101cd59293',
    messagingSenderId: '413446513130',
    projectId: 'app-fire-6dadc',
    databaseURL: 'https://app-fire-6dadc-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-6dadc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ3z-T6zcXHlYCA5PHo4QZa6Z5ZcGZKwo',
    appId: '1:413446513130:web:dc39ddbcfce27b46d59293',
    messagingSenderId: '413446513130',
    projectId: 'app-fire-6dadc',
    authDomain: 'app-fire-6dadc.firebaseapp.com',
    databaseURL: 'https://app-fire-6dadc-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-6dadc.firebasestorage.app',
  );
}
